function get_brain_image_4B()
    close all
    file_names = {'4B_ADNI_FSX_HS_DS', '4B_ADNI_FSX_HS','4B_OASIS3_ROD1_HS'};
    image_type = 'subcortical-outer-right-hemisphere';
    color_map = '''[(0,0,1), (1,1,1), (1,0,0)]''';
    for k = 1:length(file_names)
        system(['. /Users/junru/anaconda3/bin/activate && ' ...
            'conda activate /Users/junru/anaconda3/envs/temp && ' ...
            'cd ./analysis/brainpainting && ' ...
            'python brain_painting_ssh.py --traj_file_name ',file_names{k}, ...
            ' --img_type ', image_type, ...
            ' --color_map ', color_map])
    end
end